# Generated by Django 3.2 on 2021-12-16 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена'),
        ),
    ]
