# Generated by Django 3.2 on 2021-12-18 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена'),
        ),
    ]
