# Generated by Django 3.2 on 2021-12-18 13:22

from django.db import migrations
from django.db import models
from django.db.models import F, Subquery, OuterRef


def fill_order_product_price_field(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    prices_subquery = Subquery(
        OrderProduct.objects.filter(pk=OuterRef('pk')) \
                            .values('product__price')[:1]
    )
    OrderProduct.objects.filter(price=None) \
                        .update(price=prices_subquery * F('quantity'))


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_product_price_field, move_backward),
    ]
