# Generated by Django 3.2 on 2022-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20211218_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(choices=[(True, 'Обработан'), (False, 'Необработанный')], db_index=True, default=False, verbose_name='заказ обработан'),
        ),
    ]
