# Generated by Django 3.2 on 2022-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220129_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Epayment', 'Электронно'), ('Cash', 'Наличностью'), ('None', 'Не указано')], db_index=True, default='None', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
