# Generated by Django 3.2 on 2022-01-29 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocoderapp', '0002_auto_20220129_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='refreshed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='обновлено'),
        ),
    ]
